### ISSUE TITLE
Vega56风扇问题

### ISSUE THREAD

**Issue by AXIOMZK** [leafiy/Hackintosh-gigabyte-z370-ud3h-8700k-vega56#1]
老哥，我用了你的Vega补丁，风扇还是狂转，我是XFX Vega56，原版BIOS没刷，是不是必须要刷BIOS才行啊

**Comment by leafiy** [comment]
@AXIOMZK 10.14.5已经自带vega56支持了，不需要

**Comment by AXIOMZK** [comment]
好的，多谢老哥！我来升级下系统试试
